#!/usr/bin/env python3
from __future__ import annotations
import argparse, py_compile, subprocess, tempfile
from pathlib import Path

REQUIRED=[
 'framework_src/agents/unified_orchestrator.py','framework_src/agents/clinical_state_grounder.py',
 'framework_src/agents/drug_conflict_auditor.py','framework_src/agents/geriatric_risk_auditor.py',
 'framework_src/agents/alternative_agent.py','framework_src/agents/revision_agent.py',
 'framework_src/agents/trace_verifier.py','framework_src/agents/safety_critic.py',
 'framework_src/agents/evidence_sufficiency_gate.py','framework_src/pmcg/builder.py',
 'reproduce_all.sh','reproduce_POLICY_DISTILLATION_STAGE1.sh',
 '01_DEV39_WORKSPACE/policy_distillation/scripts/generate_teacher_trajectories.py',
 '01_DEV39_WORKSPACE/policy_distillation/scripts/extract_symbolic_policy.py',
 '01_DEV39_WORKSPACE/policy_distillation/scripts/verify_stage1_integrity.py',
 '01_DEV39_WORKSPACE/policy_distillation/trajectories/dev39_k1_k2_k3.jsonl',
 '01_DEV39_WORKSPACE/policy_distillation/outputs/distilled_policy_candidate.json',
 'experiments/GERIMEDBENCH/outputs/ATLAS_predictions.json',
 'experiments/CROSS_REGIONAL_SINGLE_DISEASE_GENERALIZATION_SET/outputs/ATLAS_predictions.json',
 'reproduce_BLINDED_CLINICIAN_EVALUATION.sh',
 'experiments/BLINDED_CLINICIAN_EVALUATION/scripts/prepare_blinded_clinician_review.py',
 'experiments/BLINDED_CLINICIAN_EVALUATION/scripts/aggregate_clinician_review.py',
 'experiments/BLINDED_CLINICIAN_EVALUATION/scripts/validate_reported_summary.py',
 'experiments/BLINDED_CLINICIAN_EVALUATION/scripts/verify_experiment_preservation.py',
 'experiments/BLINDED_CLINICIAN_EVALUATION/reported_results/reported_summary.json']

def main():
 p=argparse.ArgumentParser();p.add_argument('--appendix',default=None);a=p.parse_args()
 release=Path(__file__).resolve().parents[1];root=Path(a.appendix).resolve() if a.appendix else release/'CODE_APPENDIX'
 for rel in REQUIRED: assert (root/rel).exists(),rel
 # Generated bytecode is ignored; it is excluded from release manifests and ZIP builds.
 marker='# AAAI-27 paper reference:';mapped=0
 with tempfile.TemporaryDirectory() as td:
  cache=Path(td)
  for i,q in enumerate(root.rglob('*.py')):
   py_compile.compile(str(q),cfile=str(cache/f'{i}.pyc'),doraise=True)
   if marker in q.read_text(encoding='utf-8',errors='ignore'):mapped+=1
 assert mapped>=15,mapped
 for q in root.rglob('*.sh'):subprocess.run(['bash','-n',str(q)],check=True)
 western=(root/'reproduce_WESTERN_MULTIMORBIDITY_EVALUATION_SET.sh').read_text(encoding='utf-8')
 for d in ['01_DEV39_WORKSPACE/outputs','01_DEV39_WORKSPACE/results','02_FROZEN_INFERENCE/outputs','03_OFFLINE_EVALUATION/predictions','03_OFFLINE_EVALUATION/results']:
  assert d in western,d
 print(f'[OK] Code appendix verified; paper-mapped Python files: {mapped}; clean-extraction directory setup present.')
if __name__=='__main__':main()
